### ISSUE TITLE
feature request: make file socket configurable

### ISSUE THREAD

**Issue by flokli** [FreeSpacenav/spacenavd#10]
This would allow writing sockets to other locations.

As far as the client library is concerned, one could think of a discovery mechanism in paths such as `$XDG_RUNTIME_DIR/spnav.sock`, or `SPNAVD_SOCK_LOCATION` environment variable.

**Comment by jtsiomb** [comment]
What's the use case for making this configurable? What problem does it solve? It will cause chaos with existing programs not being able to talk to spacenavd, if the socket is not where they expect to find it.

**Comment by flokli** [comment]
The usecase was mostly about being able to have spacenavd not having to run as root.

Existing programs would need to be linked against a version of the library supporting that discovery logic to be able to discover, but I don't see this as chaos.

**Comment by jtsiomb** [comment]
If the security implications of running a large amount of code as root is your concern, I'm with you, but this is the wrong way to go about it. Spacenavd eventually needs to be changed to drop priviledges when executing non-driver code. All the protocol handling and X11 stuff need to run with reduced priviledges. There is a branch called `dropsu` which does this, and I do need to find the time to review and merge it to master at some point.

But all that being said and done, spacenavd is not designed as a program that users run interactively, it's a daemon that needs to be started by init as root. And given that, the current socket location makes sense, and most importantly it's part of the protocol, I cannot change it without breaking existing programs, and I will not make it configurable.

**Comment by flokli** [comment]
Running as root and dropping privileges is less secure than just running as a limited user, with the necessary udev rule plumbing in place to get access to these 6-dof devices.

If that were in place (and spacenavd wouldn't be hardcoded to write into places only root should), one could just run this as a service in the systemd user session, and automatically inherit all the necessary X11 credentials from the environment.

I however feel like we have some very differing opinions about this should be handled, and I have enough other things on my plate to keep fighting for this.

**Comment by jtsiomb** [comment]
I'm not interested in systemd and user sessions. This is designed to be a traditional UNIX daemon running from init.

**Comment by jtsiomb** [comment]
I think I explained my position clearly about this. This is not a use case I designed spacenavd for. The dropping priviledges bit is at the top of my todo list, non-daemon use is not going to be supported.

**Comment by flokli** [comment]
@Sohalt I fully agree with what you're saying. IMHO we should just ship a patch downstream instead of running this as root.

To bad upstream doesn't want to accept patches improving this situation mainline, but that shouldn't prevent us from being more secure by default.

**Comment by Sohalt** [comment]
@flokli yes, I'm afraid that's what we'll end up with. I've started work on a patch. Will probably get around to testing on the weekend.
