### ISSUE TITLE
Having trouble with connection

### ISSUE THREAD

**Issue by IlkwonHong** [FreeSpacenav/spacenavd#107]
I'm not familiar with systemd...
I followed instruction and install was finished successfully.
As my system uses systemd, so I mad symlink of contrib/spacenavd.service at /etc/systemd/system.
After that I ran add service and daemon reload

this is the output of systemctl status

● spacenavd.service - 3Dconnexion Input Devices Userspace Driver
     Loaded: loaded (/etc/systemd/system/spacenavd.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2024-06-25 16:44:05 KST; 58min ago
    Process: 932 ExecStart=/usr/local/bin/spacenavd (code=exited, status=0/SUCCESS)
   Main PID: 944 (spacenavd)
      Tasks: 1 (limit: 38089)
     Memory: 1.4M
     CGroup: /system.slice/spacenavd.service
             └─944 /usr/local/bin/spacenavd

6월 25 16:44:05 : Starting 3Dconnexion Input Devices Userspace Driver...
 6월 25 16:44:05 : Started 3Dconnexion Input Devices Userspace Driver.
Have I done right?

I want to check with example but, I can't find where they are...
Can anybody give me some help?

**Comment by jtsiomb** [comment]
This place is for bug reports, not for asking how to test spacenavd.

The example programs are part of the libspnav distribution, you can use them to test if everything is working properly: https://github.com/FreeSpacenav/libspnav
