### ISSUE TITLE
Verify status of Wireless Receiver Dongle 256f:c62f

### ISSUE THREAD

**Issue by t-paul** [FreeSpacenav/spacenavd#12]
Following up on the discussion in #4 about the `256f:c62f` wireless dongle device, here's some data from my device "[3Dconnexion SpaceMouse Wireless](https://www.3dconnexion.com/spacemouse_wireless/en/)" bought July 2015.

Note that this is not the "Universal Receiver" quoted on the webpage today. This one seems to have id `256f:c652` and name "3Dconnexion Universal Receiver" as shown in the discussion of openscad/openscad/pull/2734.

* lsusb -vv with wireless dongle connected : [lsusb.wireless-receiver.txt](https://github.com/FreeSpacenav/spacenavd/files/2898077/lsusb.wireless-receiver.txt)
* lsusb -vv with device connected via USB cable (`256f:c62e`): [lsusb.cabled.txt](https://github.com/FreeSpacenav/spacenavd/files/2898078/lsusb.cabled.txt)

As far as I can tell, the HID data sent is identical, at least via HIDAPI which we are using to connect the devices in OpenSCAD on Windows and MacOS.

Please let me know if any additional information is needed.

**Comment by jtsiomb** [comment]
Yeah that's a HID end point, so I guess that device ID should be removed from the blacklist. I'll do that now and close this bug report. If there is any further issue with this please re-open.
