### ISSUE TITLE
[Feature] Change Sensitivity live

### ISSUE THREAD

**Issue by hasechris** [FreeSpacenav/spacenavd#47]
Hi,

I'm an owner of an SpacePilot, which has some buttons around the spacemouse. I got pretty much all working in FreeCAD, so first thank you very much. This made my transition from Autodesk Inventor (they cancelled my subscription after 10 years in the education program) to FreeCAD so much nicer.

I just miss one feature here. I have two buttons to increase or decrease the sensitivity. Do you think you can make this possible? I would like to change the sensitivity "online", aka as with the ESC or STRG Keys, which are mapped to normal keyboard events; this would need to be selectable buttons (in the config file), which would increase the sensitivity on a global scale.

Best rergards
hasechris

**Comment by jtsiomb** [comment]
Yes, that's quite useful, and I thought about it before. I'll make sure to implement it sooner rather than later.

**Comment by jtsiomb** [comment]
Added a mechanism (commit 9f748d1), to bind actions to buttons through the configuration file. Buttons with bound actions are not reported to clients. Currently implemented actions: sensitivity up/down/reset. See example-spnavrc for syntax.

Closing the feature request, but any feedback, and ideas for other bindable actions, appreciated.
