### ISSUE TITLE
Friendlier output when when have spacenav library, but aren't running the mouse daemon

### ISSUE THREAD

**Issue by luzpaz** [FreeSpacenav/spacenavd#56]
Is there a standard practice to make the output of spacenav lib more friendly when it comes to output

![image](https://user-images.githubusercontent.com/4140247/152570017-37e5eec7-4c5a-4568-a6ca-588b2e9595f8.png)

This a screenshot of FreeCAD invoked from the CLI. It's calling spacenav but not finding the daemon. 

Any suggestions?

**Comment by t-paul** [comment]
I second that from OpenSCAD perspective. With the SpNav driver enabled but no deamon running the same error is shown on console and there seems to be no way to suppress that.

**Comment by jtsiomb** [comment]
These messages have been removed from libspnav two years ago in commit 844338bd699969dfc9e4577d8d268e9902002cb6

**Comment by jtsiomb** [comment]
I guess if you had to work around it in a previous version, you could do something hacky like:

    int tmpstderr = dup(2);
    close(2);
    open("/dev/null");
    ... call to spnav_open with silenced std errror output ...
    close(2);
    dup(tmpstderr);
    close(tmpstderr);

But that would be slightly absurd :)

**Comment by t-paul** [comment]
Nice it's already solved. Linux distros usually only ship released versions, so it will only appear for users once a new release of the library happens.

**Comment by jtsiomb** [comment]
I guess I could put out a minor release, I just didn't think this was an important enough change for it. I'll think about it.

**Comment by luzpaz** [comment]
:+1: for minor release

**Comment by luzpaz** [comment]
@jtsiomb would you kindly notate this ticket once a new release is made? I'd like to close the [downstream ticket](https://tracker.freecadweb.org/view.php?id=4711) to this and coordinate with the FreeCAD packagers

**Comment by t-paul** [comment]
@luzpaz better (and automatic way):

Go to repository for the client library (this one is the server part).

Select `Watch` -> `Custom` -> `Releases` and you'll automatically receive a notification from github as soon as there's a release marked.

**Comment by luzpaz** [comment]
TIL  
Thanks!

**Comment by jtsiomb** [comment]
I just released libspnav 0.3 which contains this fix.
