### ISSUE TITLE
migrate to meson

### ISSUE THREAD

**Issue by albfan** [FreeSpacenav/spacenavd#59]
Do you accept a migration in build system?

meson is probably cleaner this days, but I understand if it is not accepted, autotools just work.

Just let me know

**Comment by jtsiomb** [comment]
Thanks for the offer, but I'm not a fan of these new build systems going in and out of fashion every couple of years. I much prefer GNU make.  I think it does what it does extremely well, and doesn't get in the way.

And btw I'm not using autotools either. I find autotools extremely awkward and bloated.
