### ISSUE TITLE
Error message on Linux mint

### ISSUE THREAD

**Issue by Supermagnum** [FreeSpacenav/spacenavd#66]
./setup_init
cat: /etc/inittab: no such file
default runlevel detection failed.
selected runlevel: 2
setting up sysv init script

There is no inittab in Ubuntu based (and others non-Ubuntu) distributions.
Those uses systemd.

**Comment by jtsiomb** [comment]
I'm not sure what this bug report is about. If your system doesn't have init, why are you running `setup_init` ?
