### ISSUE TITLE
Anyone able to get the spacenavd updated in Debian experimental/unstable package repo?

### ISSUE THREAD

**Issue by luzpaz** [FreeSpacenav/spacenavd#69]
Downstream FreeCAD project would really appreciate it. 
https://packages.debian.org/sid/source/spacenavd
https://salsa.debian.org/ropp-guest/spacenavd/activity

CC @RoPP

Edit: 
Also https://github.com/FreeSpacenav/libspnav and https://github.com/FreeSpacenav/spnavcfg

**Comment by Lenglemetz** [comment]
I prefer a PPA or a snap. Maybe developers create this?

**Comment by jtsiomb** [comment]
The spacenav project does not distribute binaries, only source code. And as for the debian packaging, there's not much I can do about it, so I'm closing this issue.

**Comment by luzpaz** [comment]
Does anyone know Rodolphe Pelloux-Prayer ? Apparently they're the spacenavd debian salsa maintainer https://packages.debian.org/sid/source/spacenavd

I guess, I was hoping that someone who know this person could let them know. They haven't responded to email or the git issue ping.
