### ISSUE TITLE
Joystick output?

### ISSUE THREAD

**Issue by NXTler** [FreeSpacenav/spacenavd#77]
Hey guys!
I wanted to use my SpaceExplorer as a joystick for some time no, but couldn't find any useful information about doing it in Linux.
Is it possible to use this driver to convert my Space Explorer into a joystick or are there other ways to achieve my goal?

Thanks in advance!

**Comment by jtsiomb** [comment]
No, this driver is for feeding 6dof events to applications written specifically for it.
