### ISSUE TITLE
DEV_CADMAN and DEV_SB5000 need the DF_SWAPYZ | DF_INVYZ flags

### ISSUE THREAD

**Issue by ruevs** [FreeSpacenav/spacenavd#93]
https://github.com/FreeSpacenav/spacenavd/blob/a2d121af16628e98f523c2746ccad7b6e72c8dca/src/dev.c#L65
https://github.com/FreeSpacenav/spacenavd/blob/a2d121af16628e98f523c2746ccad7b6e72c8dca/src/dev.c#L67

I tested them personally with [my fork of libspnavdev](https://github.com/ruevs/libspnavdev/tree/USBWin32) and [SolveSpace](https://github.com/solvespace/solvespace/pull/968).

In addition to 
  - "CadMan USB"
  - "SpaceBall 5000 USB"

I also tested the following devices and verified that they need the swapping and inverting:
  - "SpaceTraveler USB"
  - "SpacePilot"
  - "SpaceExplorer"

**Comment by jtsiomb** [comment]
Thanks for reporting and verifying! Fixed.
